name: Upload Release

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: abatilo/actions-poetry@v3.0.0
      - name: Build
        run: |
          poetry install
          poetry build
      - uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          draft: true
